import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', pathMatch: 'full', loadComponent: () => import('./features/home.feature').then((m) => m.HomeFeature) },
  { path: 'basic', loadComponent: () => import('./features/basic.feature').then((m) => m.BasicFeature) },
  { path: 'sorting', loadComponent: () => import('./features/sorting.feature').then((m) => m.SortingFeature) },
  { path: 'filtering', loadComponent: () => import('./features/filtering.feature').then((m) => m.FilteringFeature) },
  { path: 'pagination', loadComponent: () => import('./features/pagination.feature').then((m) => m.PaginationFeature) },
  { path: 'selection', loadComponent: () => import('./features/selection.feature').then((m) => m.SelectionFeature) },
  { path: 'columns', loadComponent: () => import('./features/columns.feature').then((m) => m.ColumnsFeature) },
  { path: 'rendering', loadComponent: () => import('./features/rendering.feature').then((m) => m.RenderingFeature) },
  { path: 'themes', loadComponent: () => import('./features/themes.feature').then((m) => m.ThemesFeature) },
  { path: 'performance', loadComponent: () => import('./features/performance.feature').then((m) => m.PerformanceFeature) },
  { path: 'editing', loadComponent: () => import('./features/editing.feature').then((m) => m.EditingFeature) },
  { path: 'advanced-filtering', loadComponent: () => import('./features/advanced-filtering.feature').then((m) => m.AdvancedFilteringFeature) },
  { path: 'grouping', loadComponent: () => import('./features/grouping.feature').then((m) => m.GroupingFeature) },
  { path: 'tree', loadComponent: () => import('./features/tree.feature').then((m) => m.TreeFeature) },
  { path: 'master-detail', loadComponent: () => import('./features/master-detail.feature').then((m) => m.MasterDetailFeature) },
  { path: 'range', loadComponent: () => import('./features/range.feature').then((m) => m.RangeFeature) },
  { path: 'sidebar-statusbar', loadComponent: () => import('./features/sidebar-statusbar.feature').then((m) => m.SidebarStatusbarFeature) },
  { path: 'row-drag', loadComponent: () => import('./features/row-drag.feature').then((m) => m.RowDragFeature) },
  { path: 'sparklines', loadComponent: () => import('./features/sparklines.feature').then((m) => m.SparklinesFeature) },
  { path: 'export-state', loadComponent: () => import('./features/export-state.feature').then((m) => m.ExportStateFeature) },
  { path: 'api-extras', loadComponent: () => import('./features/api-extras.feature').then((m) => m.ApiExtrasFeature) },
  { path: 'pinned-rows', loadComponent: () => import('./features/pinned-rows.feature').then((m) => m.PinnedRowsFeature) },
  { path: 'column-groups', loadComponent: () => import('./features/column-groups.feature').then((m) => m.ColumnGroupsFeature) },
  { path: 'pivot', loadComponent: () => import('./features/pivot.feature').then((m) => m.PivotFeature) },
  { path: 'server-side', loadComponent: () => import('./features/server-side.feature').then((m) => m.ServerSideFeature) },
  { path: 'set-filter', loadComponent: () => import('./features/set-filter.feature').then((m) => m.SetFilterFeature) },
  { path: 'advanced-filter-builder', loadComponent: () => import('./features/advanced-filter-builder.feature').then((m) => m.AdvancedFilterBuilderFeature) },
  { path: 'wrap-text', loadComponent: () => import('./features/wrap-text.feature').then((m) => m.WrapTextFeature) },
  { path: 'lock', loadComponent: () => import('./features/lock.feature').then((m) => m.LockFeature) },
  { path: 'span', loadComponent: () => import('./features/span.feature').then((m) => m.SpanFeature) },
  { path: 'column-virt', loadComponent: () => import('./features/column-virt.feature').then((m) => m.ColumnVirtFeature) },
  { path: 'charts', loadComponent: () => import('./features/charts.feature').then((m) => m.ChartsFeature) },
  { path: 'infinite', loadComponent: () => import('./features/infinite.feature').then((m) => m.InfiniteFeature) },
  { path: 'multi-filter', loadComponent: () => import('./features/multi-filter.feature').then((m) => m.MultiFilterFeature) },
  { path: 'cell-components', loadComponent: () => import('./features/cell-components.feature').then((m) => m.CellComponentsFeature) },
  { path: 'ag-binding', loadComponent: () => import('./features/ag-binding.feature').then((m) => m.AgBindingFeature) },
  { path: 'floating-filter-component', loadComponent: () => import('./features/floating-filter-component.feature').then((m) => m.FloatingFilterComponentFeature) },
  { path: 'fit-cell-contents', loadComponent: () => import('./features/fit-cell-contents.feature').then((m) => m.FitCellContentsFeature) },
  { path: 'auto-fit-async', loadComponent: () => import('./features/auto-fit-async.feature').then((m) => m.AutoFitAsyncFeature) },
  { path: '**', redirectTo: '' },
];
// touched

